#!/bin/bash
TESTDATA=/cs/fs/home/kerola/rio_testdata/uint64-keys.bin

cd dist
java rioprojekti.RioProjekti -pmerge "$TESTDATA"
java rioprojekti.RioProjekti -pquick "$TESTDATA"
java rioprojekti.RioProjekti -squick "$TESTDATA"
